repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-ast
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-json
      - id: mixed-line-ending

  - repo: local
    hooks:
      - id: semantic-commit-msg
        name: Check semantic commit message format
        entry: python ./commons/git_hooks/enforce_semantic_commit_msg.py
        language: python
        stages: [commit-msg]

      - id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [python]
        stages: [commit]

      - id: pytest-check
        name: pytest-check
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true
        types: [python]
        stages: [commit]

      - id: pytest-cov
        name: pytest-cov
        entry: coverage run -m pytest -v --cov=app app/
        language: system
        pass_filenames: false
        always_run: true
        types: [python]
        stages: [commit]
